import type { Metadata } from "next";
import { Instrument_Serif } from "next/font/google";
import { Orbitron } from "next/font/google";
import { Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const instrumental = Instrument_Serif({
  variable: "--font-instrumental",
  subsets: ["latin"],
  weight: "400",
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: "400",
})

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${instrumental.variable} ${orbitron.variable} ${geist.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
